name: Update TestFilght Link Status

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      python_version:
        description: '指定 Python 版本 3.6+ （不建议修改）'
        required: false
        default: '3.13'

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'xuanranran/awesome-testflight-link'
    env:
      python_version: ${{ github.event.inputs.python_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Check env
        run: if [ -z "$python_version" ]; then python_version='3.13'; fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
          architecture: x64
      - name: Init Python Env
        run: pip install -r scripts/requirements.txt
      - name: Update TestFilght Link Status
        run: python scripts/update_status.py

      - name: Git commit && push
        run: |
          git_diff=`git diff`
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          git config --global user.email "github_bot@noreply.github.com"
          git config --global user.name "github_bot"
          git add .
          git commit -m "Github Action Auto Updated - `date`"
          git push

  forked-repo:
    runs-on: ubuntu-latest
    if: github.repository != 'xuanranran/awesome-testflight-link'
    
    steps:
      - uses: actions/checkout@v4

      - name: Git commit && push
        run: |
          git config --global user.email "github_bot@noreply.github.com"
          git config --global user.name "github_bot"
          git remote add upstream https://github.com/xuanranran/awesome-testflight-link.git 
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main

